### PR TITLE
BUG: fix re non-alpha

### PR DESCRIPTION
**Pull request by Hank0626**
Related to #24

### CODE REVIEW

**Comment by ChenghaoMou** [comment]
Thanks for the PR! One small issue: the negation part is missing.

**Comment by Hank0626** [comment]
'\W' (NON-Alpha) is the negation of '\w' (Alpha)

**Comment by Hank0626** [comment]
https://docs.python.org/3/library/re.html

\w
For Unicode (str) patterns:
Matches Unicode word characters; this includes alphanumeric characters (as defined by str.isalnum()) as well as the underscore (_). If the ASCII flag is used, only [a-zA-Z0-9_] is matched.

For 8-bit (bytes) patterns:
Matches characters considered alphanumeric in the ASCII character set; this is equivalent to [a-zA-Z0-9_]. If the LOCALE flag is used, matches characters considered alphanumeric in the current locale and the underscore.
\W
Matches any character which is not a word character. This is the opposite of \w. If the ASCII flag is used this becomes the equivalent of [^a-zA-Z0-9_]. If the LOCALE flag is used, matches characters which are neither alphanumeric in the current locale nor the underscore.

**Review by ChenghaoMou — APPROVED** [review]
Thanks! I missed that part. Another note on non English languages, especially CJK: If space is not present, you still need a proper tokenization method to form ngrams.

**Pull request merged**
