### PR TITLE
Doublehash minhash

### PR DESCRIPTION
**Pull request by chris-ha458**
**I do not expect this to completely replace the current minhash.**

Bloom filters also require a lot of random hashes for the purposes of their bit mask.
In their case they utilize a different methods of minimizing hash operations.
one of which is to take 2 known good hashes and permutating between them.

Our current hash derivation is as follows 
` (a * h(x) + b mod p) mod m` where x is an input to hash function h(), p is a big prime, and m is the universe size. a and b are random numbers, 1 per each hash we want.

(enhanced) Double hash is as follows

`dbh(x,i)  = ( h1(x) + i * h2(x) + f(i) mod m )` where h1,h2() are good hashes, i is an index (0 to m-1), f(i) is a function of i that can "repair" any degradations of hash quality due of the original double hash.

Most qualifications and studies are regarding bloom hash and load factors (collision when using double hash as an index generator for a table).
However, when h1 and h2 are both universal hashes, then dbh(x,i) is also within a class of universal hashes.

There are many papers on this but this one is particulary good explaining it and how it relates to count-min sketches
(for example a minhash)
https://www.eecs.harvard.edu/~michaelm/postscripts/rsa2008.pdf
(enhanced double hash is described in section 5.2 page 199 or 13/32 of the pdf)
how it relates to count-min sketches : section 9, page 214, 28/32 of the pdf

This paper discusses more on the theoretical background of hashing and how it relates to universal hashes and double hashes
https://www.cs.unc.edu/~baruah/Teaching/2017-1Sp/RestrictedAccess/LECTURES/L20-slides.pdf

Empirical data on real world data "good enough" for me
Pinecone results :
```
results of pinecone at 32 bits
{'Correct': 90320,
 'Incorrect': 9680,
 'Accuracy': 0.9032,
 'Recall': 0.9659,
 'Precision': 0.4357}
```

Compared to the previous implementation, one quality might be the most important reason I implemented this in the first place.
We no longer have to include the `PERMUTATIONS` numpy object containing random multipliers and addors (a,b) into the embedding function. 

`i` or the `index` can be derived from the index (as long as it is under max_hash it does not matter) and we can choose from a predetermined h1,h2, f(i) (usually i**2).

This way the embedding function can be much more simplified.
Anyway although I find this version interesting, it is more to be meant as a platform to implement a Rust (or Cython) based foreign function that we can easily call.

If there is actual interest into integrating this let me know what kind of changes you'd like.

I would imagine this should exist alongside minhash or as an option within.
Maybe we could extract the embed function declarations into a utility function where we can test more out.

### CODE REVIEW

**Comment by ChenghaoMou** [comment]
Thanks for the PR. Some comments:
1. I don't think MinHash (1997) is a type of Count-min Sketch (2003). MinHash is a set sketch or a type of LSH and is designed to approximate Jaccard Similarity. You can do so by simply comparing two MinHashes. Count-min Sketch is designed to characterize streaming data. You can only compare one sketch vs the query hashes to get frequency estimation or membership (e.g. Bloom filter).
2. To get $k$ hashes is important, but it is also important that the `min` part of MinHash — how it relates to set similarity — is reserved and strictly proved. I still need more direct and formal evidence to accept this change.
3. The results on the pinecone are not formal enough for this drastic change from the standard MinHash. For example, one permutation could already have the following results on that particular dataset:
```
{'Correct': 82835,
 'Incorrect': 17165,
 'Accuracy': 0.8284,
 'Recall': 0.8766,
 'Precision': 0.3811}
```
4. There are ways to reduce hashes or permutations needed, such as [C-MinHash](https://www.semanticscholar.org/paper/C-MinHash%3A-Improving-Minwise-Hashing-with-Circulant-Li-Li/d0899197294116319174f34fabcddfc32940549c) (and also note on how many experiments went into prove effectiveness).

**Comment by ChenghaoMou** [comment]
Sorry, I think I misread your code initially. Now, it is more like a fixed "permutation" or hashes salted by `index`, which I suppose makes sense. 

```
# dumb way to restructure the code for illustration
def hash_generator(salt):
  return lambda x: (sha1_hash(x) + salt * xxh3_hash(x) + salt**2) % modulo_prime
hashes = [hash_generator(i) for i in range(num_perm)]
hashvalues = np.array([[h(token) for h in hashes] for token in tokens])
```

But I am unsure how I feel about this if this is only for porting to other languages. If you want, you can create a different script for this; I prefer the standard minhash to stay intact.

**Comment by ChenghaoMou** [comment]
Could you also provide a benchmark on how much time it saves not to pass those parameters?

**Comment by chris-ha458** [comment]
Yes your current understanding of the code is in line with my own.
> If you want, you can create a different script for this; I prefer the standard minhash to stay intact.
I agree with that assessment. 

In that case would you prefer a whole new script? or for the current minhash to become a bit more modular to be able to accept different approaches to `embedfunc`s?

I am exploring alternatives to make minhash more conducive to porting to other languages while not hurting the code quality and performance of the python version. C-minhash also seems like a good option as well and I am looking into it.

**Comment by chris-ha458** [comment]
> Could you also provide a benchmark on how much time it saves not to pass those parameters?
Currently it is theoretically small, and in practice with my datasets(<1GiB datasest of OSCAR) experience it was difficult to tell as well.
It will only become apparent when either the permutations become very large (large enough that each parameter passing causes non-negligble memory allocations which I would guess>1000) or the number of items being processed (independently of the dataset size itself) become very large.

**Comment by chris-ha458** [comment]
At this point, I am open to maintaining this branch separately while we evaluate other adaptations of minhash(such as c-minhash). 
Also it might be more useful to move forward when a specific porting strategy (whether it be rust, cython etc) has been nailed down so that the specific benefits (or lack thereof) can be concretely benchmarked.

As it is, I am happy with this particular baseline from which further evaluations and comparisons could be done. 
If you feel like we should close this PR for now and reopen at a future date when some of the milestones above have been established, feel free to let me know.

**Comment by ChenghaoMou** [comment]
Let's keep it open.

On a second thought, maybe something like this:
```
def embed_func(..., minhash_strategy="doublehash", permutations=None, h1=None, h2=None):
   
    match minhash_strategy:
        case "double_hash":
            assert h1 is not None
            pass
        case "permutation":
            assert permutations is not None
            pass

if args.minhash_strategy == "permuation":
    kwargs = {"permutations": PERMUTATIONS}
elif args.minhash_strategy == "double_hash":
    kwargs = {"h1": xxh3_hash, "h2":...}

ds = ds.map(embed_func, fn_kwargs = {...} | kwargs, ...)

```

**Comment by chris-ha458** [comment]
could it be feasible to wrap `minhash_strategy="doublehash", permutations=None, h1=None, h2=None` into one dict?
for instance
```
double_hash_config  = {
    "strategy" :  "permutation",
    "permutations" : [np.ndarray, np.ndarray],
    "h1" : "sha1",
    "h2" : none,
}
```
and then similar otherwise.

**Pull request closed without merging**
