### PR TITLE
Implement Union by Rank in union_find

### PR DESCRIPTION
**Pull request by chris-ha458**
Although I spent quite some time implementing this and testing this,
I would not be upset if it was rejected outright.

It seems that for most datasets that I encounter, unionfind with path compression is good enough.

I suspect that for certain pathological datasets with high exact duplicates or near duplicates this might be relevant.
False positive / False negative ratios might also be a factor in how the union grows.
Or maybe it would be relevent in much larger scales, but in that case we would be paying the cost for the Union by Rank in this case as well. (Rank does have extremely favorable scaling characteristics though)

But it is unclear if this should implemented when it is not yet clear at this time. 
On the otherhand, having another lever for customization/optimization can always be helpful.

If you feel that the additional engineering and complexity cost is too much, I will maintain this as a branch that could be reapplied for a PR when it seems to become necessary.

### CODE REVIEW

**Comment by ChenghaoMou** [comment]
I will need more time to test this. Hopefully, we don't need to keep the original one.

**Comment by chris-ha458** [comment]
Take your time testing it in multiple datasets. I'm particularly interested in the code data you might be working with internally as they might have more duplicates, and that's where improved scaling through union by rank would shine.
I hope you can test whether the additional overhead due to the rank is worth it in your case.

Meanwhile, since there is interest, I'll flesh out the implementation for simhash and add documentation.

I will also keep this in sync with `main`

**Comment by chris-ha458** [comment]
I changed rank into a `Counter` from collections

pickled size
```
12936011
11303184
```

**Comment by chris-ha458** [comment]
I also added a microbench with the data (just 1M lines and 12MiB of soc-pokec-relationships.txt)
If this is deemed to large, I can further cut it or remove it entirely.

**Comment by chris-ha458** [comment]
I also agree that the added overhead was worthit, but to sweeten the deal I have further reduced it. 
Instead of a 100% overhead it is now around 5~15% in my testing. the specific overhead depends a lot on the data and it is logically capped on a upper limit of 100% + counter type overhead (when counter is basically used as a dict)

**Comment by chris-ha458** [comment]
I've changed some control flow and it looks and performs better than before in my opinion.
Codacy static code analysis gives a fuss about 
`return self.parent[x]` citing 
return statement in finally block may swallow exception (lost-exception W0150)
But either try succeeds or is captured and addressed by the except
(counter can only throw keyerror the way we use it and other exceptions arent handled by the previous code anyway)

Removing finally: and just have return self.parent[x] is functionally the same, and I can do that if that is called for due to performance, readability or error handling reasons.

**Review by ChenghaoMou — COMMENTED** [review]
I think what I meant previously is that we don't need to keep `UnionFind` and should just replace it with `RankUnionFind`. You might say it is better to have options, but this is where I would prefer to be opinioned, considering the added memory footprint is significantly smaller than the actual data or fingerprints.

And let's ask people to download data directly from SNAP with a link in the notebook instead of saving it in this repo.

**Comment by chris-ha458** [comment]
I completely replaced `unionfind` with `rankunionfind` taking it's name as well.
As can be confirmed by many textbook or searches, it is not uncommon to name unionfind implementations with either path compression or union by rank or both as just `unionfind`. 
I document the details in multiple ways so to avoid confusion on the difference if anybody looks.

**Review by ChenghaoMou — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
